version: "2"

linters:
    default: all
    disable:
        - cyclop
        - err113
        - depguard
        - exhaustruct
        - funlen
        - godox
        - godot
        - mnd
        - varnamelen
        - forbidigo
        - tagliatelle
        - nlreturn
        - gochecknoglobals

    settings:
        cyclop:
            max-complexity: 15
        revive:
            rules:
                - name: "exported"
                  disabled: true
