linters:
    enable-all: true
    disable:
        - depguard
        - execinquery
        - exhaustruct
        - exportloopref
        - funlen
        - godox
        - gomnd
        - mnd
        - varnamelen
        - forbidigo
        - gocognit
        - gocyclo
        - cyclop
        - err113
        - maintidx
        - tagliatelle # prefer snake_case in json fields
        - gochecknoglobals
        - gochecknoinits
        # would be nice to have but too many tests depend on environment variables, which is not allowed for t.Parallel()
        - paralleltest
        - nlreturn # find this annoying more than useful
