package hwinfo

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/numtide/nixos-facter/pkg/linux/input"
	"github.com/numtide/nixos-facter/pkg/udev"
)

// mouseBusIDs maps an input device's bus onto hwinfo's bus and mouse subclass classification.
// hwinfo's taxonomy has no equivalent for several buses; those map to other, as does any bus
// we have not seen a touchpad on before. An unrecognised bus shouldn't abort the scan.
// Apple attaches touchpads via SPI on Intel MacBooks and Apple Silicon alike (#339).
func mouseBusIDs(bus input.Bus) (*ID, *ID) {
	var busType Bus

	subClass := SubClassMouseOther

	switch bus {
	case input.BusI2c:
		busType = BusSerial
		subClass = SubClassMouseSer
	case input.BusUsb:
		busType = BusUsb
		subClass = SubClassMouseUsb
	case input.BusI8042:
		busType = BusPs2
		subClass = SubClassMousePs2
	case input.BusBluetooth:
		// Bluetooth touchpads (e.g., Apple Magic Trackpad) connect wirelessly.
		busType = BusBluetooth
	case input.BusHost:
		// Host bus for integrated devices (e.g., Apple M2 built-in trackpad).
		busType = BusHost
	case input.BusRmi, input.BusSpi:
		// RMI is a protocol which runs over other physical buses, typically i2c, but also USB or SPI.
		// SPI carries the built-in touchpads of Intel MacBooks (applespi) and Apple Silicon machines.
		busType = BusOther
	case input.BusPci, input.BusIsapnp, input.BusHil, input.BusVirtual, input.BusIsa, input.BusXtkbd,
		input.BusRs232, input.BusGameport, input.BusParport, input.BusAmiga, input.BusAdb, input.BusGsc,
		input.BusAtari, input.BusCec, input.BusIntelIshtp, input.BusAmdSfh:
		// We have not seen input devices on these buses yet; report them rather than fail the scan.
		slog.Warn("input device on unexpected bus, reporting with bus type other", "bus", bus)

		busType = BusOther
	default:
		slog.Warn("unknown input bus, reporting with bus type other", "bus", bus)

		busType = BusOther
	}

	return NewBusID(busType), &ID{
		Name:  subClass.String(),
		Value: uint16(subClass),
	}
}

// captureTouchpads scans the input devices and identifies touchpads, returning a slice of HardwareDevice structs or an
// error.
// It accepts a deviceIdx to ensure it continues on from the last device index generated by hwinfo.
func captureTouchpads(deviceIdx uint16) ([]HardwareDevice, error) {
	inputDevices, err := input.ReadDevices(nil)
	if err != nil {
		return nil, fmt.Errorf("failed to read input devices: %w", err)
	}

	var result []HardwareDevice

	for _, inputDevice := range inputDevices {
		path := "/sys" + inputDevice.Sysfs

		udevData, err := udev.Read(path)
		if errors.Is(err, udev.ErrNotFound) {
			slog.Warn("udev data not found", "name", inputDevice.Name, "sysfs", inputDevice.Sysfs)
			continue
		} else if err != nil {
			return nil, fmt.Errorf("failed to fetch udev data for device %q with udev data: %w", path, err)
		}

		if udevData.Input == nil {
			slog.Debug("udev data missing input", "name", inputDevice.Name, "sysfs", inputDevice.Sysfs)
			continue
		}

		if !udevData.Input.IsTouchpad {
			// currently, we are only interested in touchpads, as hwinfo does not capture them
			// eventually, we may take over more of the input processing that hwinfo performs
			continue
		}

		if len(inputDevice.Handlers) == 0 {
			// I believe this shouldn't be possible, and if it does occur, we should error
			return nil, fmt.Errorf("no handlers found for input device %s", inputDevice.Sysfs)
		}

		// create a hardware entry for the report
		hd := HardwareDevice{
			// todo AttachedTo: it's unclear how to work this out
			Class:     HardwareClassMouse,
			BaseClass: NewBaseClassID(BaseClassTouchpad),
			Vendor: &ID{
				Name:  udevData.Vendor,
				Value: inputDevice.Vendor,
			},
			Device: &ID{
				Name:  udevData.Model,
				Value: inputDevice.Product,
			},
			SysfsID: inputDevice.Sysfs,
		}

		hd.BusType, hd.SubClass = mouseBusIDs(inputDevice.Bus)

		// todo should we error if no event handler is found?
		if handler := inputDevice.EventHandler(); handler != "" {
			hd.UnixDeviceNames = append(hd.UnixDeviceNames, "/dev/input/"+handler)
		}

		if handler := inputDevice.MouseHandler(); handler != "" {
			hd.UnixDeviceNames = append(hd.UnixDeviceNames, "/dev/input/ + handler")
		}

		hd.Index = deviceIdx
		result = append(result, hd)

		deviceIdx++
	}

	return result, nil
}
